# Generated by Django 4.2.1 on 2023-05-24 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month',
            old_name='name',
            new_name='title',
        ),
        migrations.CreateModel(
            name='June',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.TextField(blank=True, max_length=200)),
                ('full_description', models.TextField(blank=True, max_length=800)),
                ('image', models.ImageField(upload_to='media/images/june')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.month')),
            ],
        ),
        migrations.CreateModel(
            name='July',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.TextField(blank=True, max_length=200)),
                ('full_description', models.TextField(blank=True, max_length=800)),
                ('image', models.ImageField(upload_to='media/images/july')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.month')),
            ],
        ),
        migrations.CreateModel(
            name='August',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.TextField(blank=True, max_length=200)),
                ('full_description', models.TextField(blank=True, max_length=800)),
                ('image', models.ImageField(upload_to='media/images/august')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.month')),
            ],
        ),
    ]
