# Generated by Django 4.2.1 on 2023-05-24 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_name_month_title_june_july_august'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='June',
            new_name='Sort',
        ),
        migrations.RemoveField(
            model_name='july',
            name='cat',
        ),
        migrations.DeleteModel(
            name='August',
        ),
        migrations.DeleteModel(
            name='July',
        ),
    ]
