# Generated by Django 4.2.1 on 2023-05-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_june_sort_remove_july_cat_delete_august_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sort',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
