# Generated by Django 4.2.1 on 2023-05-24 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_sort_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sort',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.month', verbose_name='Срок созревания'),
        ),
        migrations.AlterField(
            model_name='sort',
            name='full_description',
            field=models.TextField(blank=True, max_length=800, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='sort',
            name='image',
            field=models.ImageField(upload_to='media/images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='sort',
            name='short_description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='sort',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название сорта'),
        ),
    ]
