# Generated by Django 4.2.1 on 2023-05-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_sort_cat_alter_sort_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Месяц созревания'),
        ),
    ]
