# Generated by Django 4.2.1 on 2023-05-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_month_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок факта')),
                ('description', models.TextField(max_length=500, verbose_name='Содержание')),
            ],
        ),
    ]
