# Generated by Django 4.2.1 on 2023-05-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок статьи')),
                ('image', models.ImageField(upload_to='media/images', verbose_name='Изображение')),
                ('body', models.TextField(verbose_name='Содержание статьи')),
            ],
        ),
    ]
