# Generated by Django 4.2.1 on 2023-05-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Argeement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование пункта')),
                ('description', models.TextField(max_length=1000, verbose_name='Содержание пункта')),
            ],
        ),
    ]
