# Generated by Django 4.2.1 on 2023-05-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_argeement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Argeement',
            new_name='Agreement',
        ),
    ]
