# Generated by Django 4.2.1 on 2023-05-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_argeement_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Содержание пункта'),
        ),
    ]
