# Generated by Django 4.2.1 on 2023-06-02 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_amount_amount_alter_amount_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='sort',
            name='mark',
            field=models.FloatField(default=2.5, verbose_name='Оценка дегустаторов'),
        ),
        migrations.AlterField(
            model_name='amount',
            name='amount',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='amount',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='base.region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
