# Generated by Django 4.2.1 on 2023-06-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_sort_mark_alter_amount_amount_alter_amount_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='sort',
            name='mark',
            field=models.FloatField(default=5, verbose_name='Оценка дегустаторов'),
        ),
    ]
