# Generated by Django 4.2.1 on 2023-06-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_article_image_alter_sort_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='atl/images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='sort',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Изображение'),
        ),
    ]
